#!/usr/bin/env python3
# Extra paired-bootstrap tests on AP@0.5 diffs (ensemble/FCOS vs the anchor baselines).
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.analysis import load_cached, paired_ap_test
from src.ensemble import ensemble_predictions


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pred-dir", default="results/predictions")
    ap.add_argument("--out", default="results/paired_extras.json")
    ap.add_argument("--n-boot", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    models = ["fcos", "fcos_paper", "retinanet", "faster_rcnn"]
    preds, targets = load_cached(Path(args.pred_dir), models)
    print(f"Loaded {list(preds.keys())} preds, {len(targets)} targets")

    preds["ensemble"] = ensemble_predictions(
        {k: preds[k] for k in ("fcos", "retinanet")},
        iou_thr=0.55, skip_box_thr=0.01,
    )

    pairs = [
        ("fcos_paper_vs_retinanet", "fcos_paper", "retinanet"),
        ("ensemble_vs_retinanet",   "ensemble",   "retinanet"),
        ("ensemble_vs_faster_rcnn", "ensemble",   "faster_rcnn"),
        ("fcos_paper_vs_faster_rcnn", "fcos_paper", "faster_rcnn"),
    ]
    out = {}
    for name, a, b in pairs:
        diff, lo, hi, p = paired_ap_test(
            preds[a], preds[b], targets, n_boot=args.n_boot, seed=args.seed,
        )
        print(f"{name:>32s}: {diff*100:+.2f} pts  "
              f"95% CI [{lo*100:+.2f}, {hi*100:+.2f}]  p={p:.4f}")
        out[name] = {"diff": diff, "lo95": lo, "hi95": hi, "p_two_sided": p,
                     "n_boot": args.n_boot}

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"\nWrote {args.out}")

    # LaTeX fragment
    labels = {
        "fcos_paper_vs_retinanet": ("FCOS (SGD)", "RetinaNet"),
        "ensemble_vs_retinanet": ("Ensemble (FCOS+Retina)", "RetinaNet"),
        "ensemble_vs_faster_rcnn": ("Ensemble (FCOS+Retina)", "Faster R-CNN"),
        "fcos_paper_vs_faster_rcnn": ("FCOS (SGD)", "Faster R-CNN"),
    }
    tex_path = Path(args.out).parent / "paired_extras.tex"
    rows = []
    for k, (a, b) in labels.items():
        r = out[k]
        rows.append(
            f"{a} $-$ {b} & ${r['diff']*100:+.2f}$ & "
            f"$[{r['lo95']*100:+.2f},\\,{r['hi95']*100:+.2f}]$ & "
            f"${r['p_two_sided']:.3f}$ \\\\"
        )
    tex = (
        "% Auto-generated by scripts/paired_bootstrap_extras.py\n"
        "\\begin{table}[H]\n\\centering\\small\n"
        "\\caption{Paired bootstrap on AP@0.5 differences "
        "($B = " + str(args.n_boot) + "$ resamples of validation patients). "
        "$p$-values are two-sided; no Holm/Bonferroni correction is applied --- "
        "a Bonferroni adjustment for the family of four tests would set "
        "$\\alpha = 0.0125$.}\n"
        "\\label{tab:paired-extras}\n"
        "\\begin{tabular}{lccc}\n\\toprule\n"
        "Comparison & $\\Delta$ AP@0.5 (pts) & $95\\%$ CI & $p$ (two-sided) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n"
        "\\end{tabular}\n\\end{table}\n"
    )
    tex_path.write_text(tex)
    print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()